// Generated by scripts/generate-lucide-paths.py; do not edit.
// Lucide SVG source and license: assets/lucide/README.md.
use super::Kind;
use tiny_skia::{Path, PathBuilder};
pub(super) fn paths(kind: Kind) -> Vec<(Path, bool)> {
    match kind {
        Kind::Play => vec![{
            let mut path = PathBuilder::new();
            path.move_to(5.0, 5.0);
            path.cubic_to(4.999788, 4.28371, 5.382652, 3.621998, 6.003751, 3.265196);
            path.cubic_to(6.62485, 2.908395, 7.389338, 2.91099, 8.008, 3.272);
            path.line_to(20.005, 10.27);
            path.cubic_to(20.62114, 10.62752, 21.00062, 11.28578, 21.00124, 11.99814);
            path.cubic_to(21.00185, 12.71049, 20.62352, 13.36941, 20.008, 13.728);
            path.line_to(8.008, 20.728);
            path.cubic_to(7.389338, 21.08901, 6.62485, 21.09161, 6.003751, 20.7348);
            path.cubic_to(5.382652, 20.378, 4.999788, 19.71629, 5.0, 19.0);
            path.close();
            (path.finish().expect("pinned Lucide path"), true)
        }],
        Kind::Pause => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(15.0, 3.0);
                path.line_to(18.0, 3.0);
                path.cubic_to(18.55228, 3.0, 19.0, 3.447715, 19.0, 4.0);
                path.line_to(19.0, 20.0);
                path.cubic_to(19.0, 20.55228, 18.55228, 21.0, 18.0, 21.0);
                path.line_to(15.0, 21.0);
                path.cubic_to(14.44772, 21.0, 14.0, 20.55228, 14.0, 20.0);
                path.line_to(14.0, 4.0);
                path.cubic_to(14.0, 3.447715, 14.44772, 3.0, 15.0, 3.0);
                path.close();
                (path.finish().expect("pinned Lucide path"), true)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(6.0, 3.0);
                path.line_to(9.0, 3.0);
                path.cubic_to(9.552285, 3.0, 10.0, 3.447715, 10.0, 4.0);
                path.line_to(10.0, 20.0);
                path.cubic_to(10.0, 20.55228, 9.552285, 21.0, 9.0, 21.0);
                path.line_to(6.0, 21.0);
                path.cubic_to(5.447715, 21.0, 5.0, 20.55228, 5.0, 20.0);
                path.line_to(5.0, 4.0);
                path.cubic_to(5.0, 3.447715, 5.447715, 3.0, 6.0, 3.0);
                path.close();
                (path.finish().expect("pinned Lucide path"), true)
            },
        ],
        Kind::Previous => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(17.971, 4.285);
                path.cubic_to(18.58886, 3.914277, 19.35838, 3.904568, 19.9854, 4.259583);
                path.cubic_to(20.61242, 4.614598, 21.00001, 5.279451, 21.0, 6.0);
                path.line_to(21.0, 18.0);
                path.cubic_to(21.00001, 18.72055, 20.61242, 19.3854, 19.9854, 19.74042);
                path.cubic_to(19.35838, 20.09543, 18.58886, 20.08572, 17.971, 19.715);
                path.line_to(7.974, 13.717);
                path.cubic_to(7.370313, 13.35631, 7.000413, 12.70508, 6.999799, 12.00185);
                path.cubic_to(6.999184, 11.29862, 7.367945, 10.64674, 7.971, 10.285);
                path.close();
                (path.finish().expect("pinned Lucide path"), true)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(3.0, 20.0);
                path.line_to(3.0, 4.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
        ],
        Kind::Next => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(21.0, 4.0);
                path.line_to(21.0, 20.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(6.029, 4.285);
                path.cubic_to(5.411136, 3.914277, 4.641619, 3.904568, 4.014598, 4.259583);
                path.cubic_to(3.387577, 4.614598, 2.999993, 5.279451, 3.0, 6.0);
                path.line_to(3.0, 18.0);
                path.cubic_to(2.999993, 18.72055, 3.387577, 19.3854, 4.014598, 19.74042);
                path.cubic_to(4.641619, 20.09543, 5.411136, 20.08572, 6.029, 19.715);
                path.line_to(16.026, 13.717);
                path.cubic_to(16.62969, 13.35631, 16.99959, 12.70508, 17.0002, 12.00185);
                path.cubic_to(17.00082, 11.29862, 16.63206, 10.64674, 16.029, 10.285);
                path.close();
                (path.finish().expect("pinned Lucide path"), true)
            },
        ],
        Kind::Repeat => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(17.0, 2.0);
                path.line_to(21.0, 6.0);
                path.line_to(17.0, 10.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(3.0, 11.0);
                path.line_to(3.0, 10.0);
                path.cubic_to(3.0, 7.790861, 4.790861, 6.0, 7.0, 6.0);
                path.line_to(21.0, 6.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(7.0, 22.0);
                path.line_to(3.0, 18.0);
                path.line_to(7.0, 14.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(21.0, 13.0);
                path.line_to(21.0, 14.0);
                path.cubic_to(21.0, 16.20914, 19.20914, 18.0, 17.0, 18.0);
                path.line_to(3.0, 18.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
        ],
        Kind::RepeatOne => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(17.0, 2.0);
                path.line_to(21.0, 6.0);
                path.line_to(17.0, 10.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(3.0, 11.0);
                path.line_to(3.0, 10.0);
                path.cubic_to(3.0, 7.790861, 4.790861, 6.0, 7.0, 6.0);
                path.line_to(21.0, 6.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(7.0, 22.0);
                path.line_to(3.0, 18.0);
                path.line_to(7.0, 14.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(21.0, 13.0);
                path.line_to(21.0, 14.0);
                path.cubic_to(21.0, 16.20914, 19.20914, 18.0, 17.0, 18.0);
                path.line_to(3.0, 18.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(11.0, 10.0);
                path.line_to(12.0, 10.0);
                path.line_to(12.0, 14.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
        ],
        Kind::Shuffle => vec![
            {
                let mut path = PathBuilder::new();
                path.move_to(18.0, 14.0);
                path.line_to(22.0, 18.0);
                path.line_to(18.0, 22.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(18.0, 2.0);
                path.line_to(22.0, 6.0);
                path.line_to(18.0, 10.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(2.0, 18.0);
                path.line_to(3.973, 18.0);
                path.cubic_to(5.285265, 18.00896, 6.51846, 17.37368, 7.273, 16.3);
                path.line_to(12.727, 7.7);
                path.cubic_to(13.48154, 6.626319, 14.71473, 5.991037, 16.027, 6.0);
                path.line_to(22.0, 6.0);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(2.0, 6.0);
                path.line_to(3.972, 6.0);
                path.cubic_to(5.492627, 5.989417, 6.887738, 6.841985, 7.572, 8.2);
                (path.finish().expect("pinned Lucide path"), false)
            },
            {
                let mut path = PathBuilder::new();
                path.move_to(22.0, 18.0);
                path.line_to(15.959, 18.0);
                path.cubic_to(14.62803, 17.98642, 13.391, 17.31168, 12.659, 16.2);
                path.line_to(12.3, 15.75);
                (path.finish().expect("pinned Lucide path"), false)
            },
        ],
    }
}
