[package]
name = "towavue-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "towavue"
path = "src/main.rs"

[dependencies]
egui = "=0.35.0"
egui-winit = { version = "=0.35.0", default-features = false, features = ["accesskit", "clipboard"] }
towavue-core = { path = "../towavue-core" }
towavue-runtime-windows = { path = "../towavue-runtime-windows" }
winit = "=0.30.13"

[lints]
workspace = true
