[package]
name = "towavue-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "towavue"
path = "src/main.rs"

[dependencies]
towavue-core = { path = "../towavue-core" }
towavue-runtime-windows = { path = "../towavue-runtime-windows" }
winit = "=0.30.12"

[lints]
workspace = true
