//! Shared app-owned display text. Persist command identifiers, never these labels.

use crate::CommandId;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum Language {
    #[default]
    English,
    Japanese,
}

impl Language {
    pub const fn code(self) -> &'static str {
        match self {
            Self::English => "en",
            Self::Japanese => "ja",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "en" => Some(Self::English),
            "ja" => Some(Self::Japanese),
            _ => None,
        }
    }
}

mod catalog;
pub mod formatted;
pub use catalog::Text;

/// Keep persisted command IDs independent of translated display titles.
pub const fn command_text(command: CommandId) -> Text {
    match command {
        CommandId::OpenFile => Text::CommandOpenFile,
        CommandId::PasteImage => Text::CommandPasteImage,
        CommandId::ToggleFullscreen => Text::CommandToggleFullscreen,
        CommandId::OpenFolder => Text::CommandOpenFolder,
        CommandId::OpenGallery => Text::CommandOpenGallery,
        CommandId::GoToFile => Text::CommandGoToFile,
        CommandId::OpenRecentFolder => Text::CommandOpenRecentFolder,
        CommandId::ShowLicenses => Text::CommandShowLicenses,
        CommandId::About => Text::CommandAbout,
        CommandId::CheckForUpdates => Text::CommandCheckForUpdates,
        CommandId::CloseTab => Text::CommandCloseTab,
        CommandId::NextTab => Text::CommandNextTab,
        CommandId::PreviousTab => Text::CommandPreviousTab,
        CommandId::TogglePause => Text::CommandTogglePause,
        CommandId::PlayTimeSelection => Text::CommandPlayTimeSelection,
        CommandId::CycleAudioRepeat => Text::CommandCycleAudioRepeat,
        CommandId::CycleAudioTrack => Text::CommandCycleAudioTrack,
        CommandId::ToggleVideoRepeat => Text::CommandToggleVideoRepeat,
        CommandId::ToggleAudioShuffle => Text::CommandToggleAudioShuffle,
        CommandId::SeekBackward => Text::CommandSeekBackward,
        CommandId::SeekForward => Text::CommandSeekForward,
        CommandId::SeekVideo0 => Text::CommandSeekVideo0,
        CommandId::SeekVideo10 => Text::CommandSeekVideo10,
        CommandId::SeekVideo20 => Text::CommandSeekVideo20,
        CommandId::SeekVideo30 => Text::CommandSeekVideo30,
        CommandId::SeekVideo40 => Text::CommandSeekVideo40,
        CommandId::SeekVideo50 => Text::CommandSeekVideo50,
        CommandId::SeekVideo60 => Text::CommandSeekVideo60,
        CommandId::SeekVideo70 => Text::CommandSeekVideo70,
        CommandId::SeekVideo80 => Text::CommandSeekVideo80,
        CommandId::SeekVideo90 => Text::CommandSeekVideo90,
        CommandId::PreviousMedia => Text::CommandPreviousMedia,
        CommandId::NextMedia => Text::CommandNextMedia,
        CommandId::PreviousSameKind => Text::CommandPreviousSameKind,
        CommandId::NextSameKind => Text::CommandNextSameKind,
        CommandId::ToggleFilmstrip => Text::CommandToggleFilmstrip,
        CommandId::ToggleCommandPalette => Text::CommandToggleCommandPalette,
        CommandId::OpenKeyboardSettings => Text::CommandOpenKeyboardSettings,
        CommandId::ReloadShortcuts => Text::CommandReloadShortcuts,
        CommandId::ZoomIn => Text::CommandZoomIn,
        CommandId::ZoomOut => Text::CommandZoomOut,
        CommandId::ActualSize => Text::CommandActualSize,
        CommandId::FitToWindow => Text::CommandFitToWindow,
        CommandId::CoverWindow => Text::CommandCoverWindow,
        CommandId::SelectAll => Text::CommandSelectAll,
        CommandId::ClearSelection => Text::CommandClearSelection,
        CommandId::ZoomSelection => Text::CommandZoomSelection,
        CommandId::ToggleReadingMode => Text::CommandToggleReadingMode,
        CommandId::ReadingLeft => Text::CommandReadingLeft,
        CommandId::ReadingRight => Text::CommandReadingRight,
        CommandId::IncreaseReadingPages => Text::CommandIncreaseReadingPages,
        CommandId::DecreaseReadingPages => Text::CommandDecreaseReadingPages,
        CommandId::ToggleReadingAxis => Text::CommandToggleReadingAxis,
        CommandId::ReverseReadingOrder => Text::CommandReverseReadingOrder,
        CommandId::ReloadFolderOrder => Text::CommandReloadFolderOrder,
        CommandId::Undo => Text::CommandUndo,
        CommandId::Redo => Text::CommandRedo,
        CommandId::ApplyCrop => Text::CommandApplyCrop,
        CommandId::RotateClockwise => Text::CommandRotateClockwise,
        CommandId::RotateCounterclockwise => Text::CommandRotateCounterclockwise,
        CommandId::RotateFineClockwise => Text::CommandRotateFineClockwise,
        CommandId::RotateFineCounterclockwise => Text::CommandRotateFineCounterclockwise,
        CommandId::FlipHorizontal => Text::CommandFlipHorizontal,
        CommandId::FlipVertical => Text::CommandFlipVertical,
        CommandId::SetTrimStart => Text::CommandSetTrimStart,
        CommandId::SetTrimEnd => Text::CommandSetTrimEnd,
        CommandId::DeleteTimeSelection => Text::CommandDeleteTimeSelection,
        CommandId::KeepTimeSelection => Text::CommandKeepTimeSelection,
        CommandId::VolumeDown => Text::CommandVolumeDown,
        CommandId::VolumeUp => Text::CommandVolumeUp,
        CommandId::ToggleMute => Text::CommandToggleMute,
        CommandId::CycleVolumeStep => Text::CommandCycleVolumeStep,
        CommandId::VolumeStepTwo => Text::CommandVolumeStepTwo,
        CommandId::VolumeStepFive => Text::CommandVolumeStepFive,
        CommandId::VolumeStepTen => Text::CommandVolumeStepTen,
        CommandId::AudioRepeatOff => Text::CommandAudioRepeatOff,
        CommandId::AudioRepeatAll => Text::CommandAudioRepeatAll,
        CommandId::AudioRepeatOne => Text::CommandAudioRepeatOne,
        CommandId::FolderNavigationStop => Text::CommandFolderNavigationStop,
        CommandId::FolderNavigationLoop => Text::CommandFolderNavigationLoop,
        CommandId::RateDown => Text::CommandRateDown,
        CommandId::RateUp => Text::CommandRateUp,
        CommandId::ResetRate => Text::CommandResetRate,
        CommandId::EditSpeed => Text::CommandEditSpeed,
        CommandId::DeleteFile => Text::CommandDeleteFile,
        CommandId::RenameFile => Text::CommandRenameFile,
        CommandId::MoveFile => Text::CommandMoveFile,
        CommandId::Save => Text::CommandSave,
        CommandId::ExportAs => Text::CommandExportAs,
        CommandId::AudioExportOptions => Text::CommandAudioExportOptions,
        CommandId::MetadataExportOptions => Text::CommandMetadataExportOptions,
        CommandId::ExportAudio => Text::CommandExportAudio,
        CommandId::ExportFrame => Text::CommandExportFrame,
        CommandId::ToggleTimeline => Text::CommandToggleTimeline,
        CommandId::ToggleGridMenu => Text::CommandToggleGridMenu,
        CommandId::ExportQualityHigh => Text::CommandExportQualityHigh,
        CommandId::ExportQualityBalanced => Text::CommandExportQualityBalanced,
        CommandId::ExportQualitySmaller => Text::CommandExportQualitySmaller,
        CommandId::ToggleHardwareEncode => Text::CommandToggleHardwareEncode,
        CommandId::PreviousImage => Text::CommandPreviousImage,
        CommandId::NextImage => Text::CommandNextImage,
        CommandId::FirstImage => Text::CommandFirstImage,
        CommandId::LastImage => Text::CommandLastImage,
        CommandId::IncreaseReadingFirstPage => Text::CommandIncreaseReadingFirstPage,
        CommandId::DecreaseReadingFirstPage => Text::CommandDecreaseReadingFirstPage,
        CommandId::CloseOtherTabs => Text::CommandCloseOtherTabs,
        CommandId::CloseTabsLeft => Text::CommandCloseTabsLeft,
        CommandId::CloseTabsRight => Text::CommandCloseTabsRight,
        CommandId::CloseAllTabs => Text::CommandCloseAllTabs,
        CommandId::ReopenClosedTab => Text::CommandReopenClosedTab,
        CommandId::CopyFilePath => Text::CommandCopyFilePath,
        CommandId::RevealFile => Text::CommandRevealFile,
        CommandId::CopyImage => Text::CommandCopyImage,
        CommandId::ResizeImage => Text::CommandResizeImage,
        CommandId::ToggleImageInterpolation => Text::CommandToggleImageInterpolation,
        CommandId::ToggleImageMinification => Text::CommandToggleImageMinification,
        CommandId::PreviousVideoFrame => Text::CommandPreviousVideoFrame,
        CommandId::NextVideoFrame => Text::CommandNextVideoFrame,
        CommandId::JumpImagesBackward1 => Text::CommandJumpImagesBackward1,
        CommandId::JumpImagesBackward2 => Text::CommandJumpImagesBackward2,
        CommandId::JumpImagesBackward3 => Text::CommandJumpImagesBackward3,
        CommandId::JumpImagesBackward4 => Text::CommandJumpImagesBackward4,
        CommandId::JumpImagesBackward5 => Text::CommandJumpImagesBackward5,
        CommandId::JumpImagesBackward6 => Text::CommandJumpImagesBackward6,
        CommandId::JumpImagesBackward7 => Text::CommandJumpImagesBackward7,
        CommandId::JumpImagesBackward8 => Text::CommandJumpImagesBackward8,
        CommandId::JumpImagesBackward9 => Text::CommandJumpImagesBackward9,
        CommandId::JumpImagesBackward10 => Text::CommandJumpImagesBackward10,
        CommandId::JumpImagesForward1 => Text::CommandJumpImagesForward1,
        CommandId::JumpImagesForward2 => Text::CommandJumpImagesForward2,
        CommandId::JumpImagesForward3 => Text::CommandJumpImagesForward3,
        CommandId::JumpImagesForward4 => Text::CommandJumpImagesForward4,
        CommandId::JumpImagesForward5 => Text::CommandJumpImagesForward5,
        CommandId::JumpImagesForward6 => Text::CommandJumpImagesForward6,
        CommandId::JumpImagesForward7 => Text::CommandJumpImagesForward7,
        CommandId::JumpImagesForward8 => Text::CommandJumpImagesForward8,
        CommandId::JumpImagesForward9 => Text::CommandJumpImagesForward9,
        CommandId::JumpImagesForward10 => Text::CommandJumpImagesForward10,
        CommandId::SelectAspectSquare => Text::CommandSelectAspectSquare,
        CommandId::SelectAspectFourThree => Text::CommandSelectAspectFourThree,
        CommandId::SelectAspectThreeFour => Text::CommandSelectAspectThreeFour,
        CommandId::SelectAspectThreeTwo => Text::CommandSelectAspectThreeTwo,
        CommandId::SelectAspectTwoThree => Text::CommandSelectAspectTwoThree,
        CommandId::SelectAspectSixteenNine => Text::CommandSelectAspectSixteenNine,
        CommandId::SelectAspectNineSixteen => Text::CommandSelectAspectNineSixteen,
        CommandId::FreeRotateImage => Text::CommandFreeRotateImage,
        CommandId::FreeRotateVideo => Text::CommandFreeRotateVideo,
        CommandId::ResizeVideo => Text::CommandResizeVideo,
        CommandId::StepAudioBackward => Text::CommandStepAudioBackward,
        CommandId::StepAudioForward => Text::CommandStepAudioForward,
    }
}
