"""Generate the seven pinned Lucide paths offline, using only the Python stdlib."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "crates/towavue-app/assets/lucide"
OUTPUT = ROOT / "crates/towavue-app/src/lucide/paths.rs"
ICONS = {"Play": "play", "Pause": "pause", "Previous": "skip-back",
         "Next": "skip-forward", "Repeat": "repeat", "RepeatOne": "repeat-1",
         "Shuffle": "shuffle"}


def number(value):
    result = f"{value:.7g}" if abs(value) >= 1e-7 else "0"
    return result + ".0" if "." not in result and "e" not in result else result


def arc(start, rx, ry, rotation, large, sweep, end):
    """SVG endpoint arc to cubic segments, each spanning at most a quarter turn."""
    assert large in (0, 1) and sweep in (0, 1)
    if start == end:
        return []
    if rx == 0 or ry == 0:
        return [("line_to", end)]
    rx, ry = abs(rx), abs(ry)
    phi = math.radians(rotation)
    cos, sin = math.cos(phi), math.sin(phi)
    dx, dy = (start[0] - end[0]) / 2, (start[1] - end[1]) / 2
    x, y = cos * dx + sin * dy, -sin * dx + cos * dy
    factor = math.sqrt(max(1, x*x/(rx*rx) + y*y/(ry*ry)))
    rx, ry = rx * factor, ry * factor
    quotient = max(0, (rx*rx*ry*ry - rx*rx*y*y - ry*ry*x*x)
                   / (rx*rx*y*y + ry*ry*x*x))
    coefficient = (-1 if large == sweep else 1) * math.sqrt(quotient)
    cx, cy = coefficient * rx*y/ry, coefficient * -ry*x/rx
    center = (cos*cx - sin*cy + (start[0]+end[0])/2,
              sin*cx + cos*cy + (start[1]+end[1])/2)
    u, v = ((x-cx)/rx, (y-cy)/ry), ((-x-cx)/rx, (-y-cy)/ry)
    theta = math.atan2(u[1], u[0])
    delta = math.atan2(u[0]*v[1]-u[1]*v[0], u[0]*v[0]+u[1]*v[1])
    if sweep and delta < 0:
        delta += 2*math.pi
    if not sweep and delta > 0:
        delta -= 2*math.pi
    segments = max(1, math.ceil(abs(delta) / (math.pi/2)))
    step = delta / segments

    def point(angle):
        return (center[0] + rx*cos*math.cos(angle) - ry*sin*math.sin(angle),
                center[1] + rx*sin*math.cos(angle) + ry*cos*math.sin(angle))

    def tangent(angle):
        return (-rx*cos*math.sin(angle) - ry*sin*math.cos(angle),
                -rx*sin*math.sin(angle) + ry*cos*math.cos(angle))

    result = []
    for index in range(segments):
        a, b = theta + index*step, theta + (index+1)*step
        p, q, t, w = point(a), point(b), tangent(a), tangent(b)
        weight = 4/3 * math.tan(step/4)
        last = end if index == segments-1 else q
        result.append(("cubic_to", (p[0]+weight*t[0], p[1]+weight*t[1],
                                    q[0]-weight*w[0], q[1]-weight*w[1], *last)))
    return result


def parse(data):
    token = r"[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?"
    assert not re.sub(token, "", data).replace(",", "").strip()
    tokens = re.findall(token, data)
    current, initial, command, result, closed = (0, 0), (0, 0), None, [], False
    while tokens:
        if tokens[0].isalpha():
            command = tokens.pop(0)
        assert command is not None
        kind = command.upper()
        relative = command.islower()
        if kind == "Z":
            result.append(("close", ()))
            current, command, closed = initial, None, True
            continue
        count = {"M": 2, "L": 2, "H": 1, "V": 1, "A": 7}[kind]
        values = [float(tokens.pop(0)) for _ in range(count)]
        if kind in ("M", "L"):
            end = tuple(values[i] + (current[i] if relative else 0) for i in range(2))
            result.append(("move_to" if kind == "M" else "line_to", end))
            if kind == "M":
                initial, command = end, "l" if relative else "L"
        elif kind == "H":
            end = (values[0] + (current[0] if relative else 0), current[1])
            result.append(("line_to", end))
        elif kind == "V":
            end = (current[0], values[0] + (current[1] if relative else 0))
            result.append(("line_to", end))
        else:
            end = tuple(values[5+i] + (current[i] if relative else 0) for i in range(2))
            result.extend(arc(current, *values[:5], end))
        current = end
    return result, closed


def generate():
    manifest = json.loads((ASSETS / "upstream.json").read_text(encoding="utf-8"))
    for name, digest in manifest["sha256"].items():
        assert hashlib.sha256((ASSETS/name).read_bytes()).hexdigest() == digest, name
    lines = ["// Generated by scripts/generate-lucide-paths.py; do not edit.",
             "// Lucide SVG source and license: assets/lucide/README.md.",
             "use super::Kind;", "use tiny_skia::{Path, PathBuilder};",
             "pub(super) fn paths(kind: Kind) -> Vec<(Path, bool)> {", "match kind {"]
    for kind, name in ICONS.items():
        svg = ET.parse(ASSETS / (name + ".svg")).getroot()
        assert svg.attrib["viewBox"] == "0 0 24 24"
        lines.append(f"Kind::{kind} => vec![")
        for element in svg:
            tag = element.tag.split("}")[-1]
            if tag == "path":
                assert set(element.attrib) == {"d"}
                commands, closed = parse(element.attrib["d"])
            else:
                assert tag == "rect" and set(element.attrib) == {"x", "y", "width", "height", "rx"}
                x, y, width, height, radius = [float(element.attrib[k]) for k in ("x", "y", "width", "height", "rx")]
                commands, closed = parse(f"M{x+radius} {y} H{x+width-radius} A{radius} {radius} 0 0 1 {x+width} {y+radius} V{y+height-radius} A{radius} {radius} 0 0 1 {x+width-radius} {y+height} H{x+radius} A{radius} {radius} 0 0 1 {x} {y+height-radius} V{y+radius} A{radius} {radius} 0 0 1 {x+radius} {y} Z")
            lines.append("{ let mut path = PathBuilder::new();")
            for method, values in commands:
                lines.append(f"path.{method}({', '.join(number(v) for v in values)});")
            lines.append(f'(path.finish().expect("pinned Lucide path"), {str(closed).lower()}) }},')
        lines.append("],")
    lines.extend(["}", "}"])
    return subprocess.run(["rustfmt", "--emit", "stdout", "--edition", "2024"],
                          input="\n".join(lines), capture_output=True, text=True,
                          check=True, cwd=ROOT).stdout.replace("\r\n", "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    generated = generate().encode("utf-8")
    if options.check:
        assert OUTPUT.read_bytes() == generated, "Lucide paths need regeneration"
        print("Pinned SVG hashes and generated Lucide paths match.")
    else:
        OUTPUT.parent.mkdir(exist_ok=True)
        OUTPUT.write_bytes(generated)
