//! English and Japanese catalog. Every key requires both translations.
use super::Language;

macro_rules! messages {
    ($($key:ident => ($english:literal, $japanese:literal),)*) => {
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Text { $($key,)* }

        impl Text {
            pub const fn in_language(self, language: Language) -> &'static str {
                match (self, language) {
                    $((Self::$key, Language::English) => $english,
                      (Self::$key, Language::Japanese) => $japanese,)*
                }
            }
        }
    };
}

messages! {
    CommandOpenFile => ("Open file", "ファイルを開く"),
    CommandPasteImage => ("Paste image", "画像を貼り付け"),
    CommandToggleFullscreen => ("Toggle fullscreen", "全画面表示を切り替え"),
    CommandOpenFolder => ("Open folder", "フォルダーを開く"),
    CommandOpenGallery => ("Open Gallery", "ギャラリーを開く"),
    CommandGoToFile => ("Go to File", "ファイルへ移動"),
    CommandOpenRecentFolder => ("Open Recent Folder", "最近使ったフォルダーを開く"),
    CommandShowLicenses => ("Show licenses and sources", "ライセンスとソースを表示"),
    CommandAbout => ("About towavue", "towavueについて"),
    CommandCheckForUpdates => ("Check for updates", "更新を確認"),
    CommandCloseTab => ("Close tab", "タブを閉じる"),
    CommandNextTab => ("Next tab", "次のタブ"),
    CommandPreviousTab => ("Previous tab", "前のタブ"),
    CommandTogglePause => ("Play or pause", "再生／一時停止"),
    CommandPlayTimeSelection => ("Play selected time", "選択した時間範囲を再生"),
    CommandCycleAudioRepeat => ("Cycle audio repeat", "音声のリピート方法を切り替え"),
    CommandToggleVideoRepeat => ("Toggle video repeat", "動画のリピートを切り替え"),
    CommandToggleAudioShuffle => ("Toggle audio shuffle", "音声のシャッフルを切り替え"),
    CommandSeekBackward => ("Seek backward", "再生位置を戻す"),
    CommandSeekForward => ("Seek forward", "再生位置を進める"),
    CommandSeekVideo0 => ("Seek video to 0%", "動画の0%の位置へ移動"),
    CommandSeekVideo10 => ("Seek video to 10%", "動画の10%の位置へ移動"),
    CommandSeekVideo20 => ("Seek video to 20%", "動画の20%の位置へ移動"),
    CommandSeekVideo30 => ("Seek video to 30%", "動画の30%の位置へ移動"),
    CommandSeekVideo40 => ("Seek video to 40%", "動画の40%の位置へ移動"),
    CommandSeekVideo50 => ("Seek video to 50%", "動画の50%の位置へ移動"),
    CommandSeekVideo60 => ("Seek video to 60%", "動画の60%の位置へ移動"),
    CommandSeekVideo70 => ("Seek video to 70%", "動画の70%の位置へ移動"),
    CommandSeekVideo80 => ("Seek video to 80%", "動画の80%の位置へ移動"),
    CommandSeekVideo90 => ("Seek video to 90%", "動画の90%の位置へ移動"),
    CommandPreviousMedia => ("Previous media", "前のメディア"),
    CommandNextMedia => ("Next media", "次のメディア"),
    CommandPreviousSameKind => ("Previous media of same kind", "同じ種類の前のメディア"),
    CommandNextSameKind => ("Next media of same kind", "同じ種類の次のメディア"),
    CommandToggleFilmstrip => ("Toggle filmstrip", "フィルムストリップを切り替え"),
    CommandToggleCommandPalette => ("Show command palette", "コマンドパレットを表示"),
    CommandOpenKeyboardSettings => ("Keyboard Shortcuts", "キーボードショートカット"),
    CommandReloadShortcuts => ("Reload keyboard shortcuts", "キーボードショートカットを再読み込み"),
    CommandZoomIn => ("Zoom in", "拡大"),
    CommandZoomOut => ("Zoom out", "縮小"),
    CommandActualSize => ("Zoom to actual size", "実寸で表示"),
    CommandFitToWindow => ("Fit media to window", "ウィンドウに収める"),
    CommandCoverWindow => ("Cover window with media", "ウィンドウを埋める"),
    CommandSelectAll => ("Select all", "すべて選択"),
    CommandClearSelection => ("Deselect all", "選択を解除"),
    CommandZoomSelection => ("Zoom to selection", "選択範囲を拡大表示"),
    CommandToggleReadingMode => ("Toggle reading mode", "読書モードを切り替え"),
    CommandReadingLeft => ("Move reading spread left", "見開きを左へ移動"),
    CommandReadingRight => ("Move reading spread right", "見開きを右へ移動"),
    CommandIncreaseReadingPages => ("Show more reading pages", "同時に表示するページを増やす"),
    CommandDecreaseReadingPages => ("Show fewer reading pages", "同時に表示するページを減らす"),
    CommandToggleReadingAxis => ("Toggle reading layout axis", "読書モードの配置方向を切り替え"),
    CommandReverseReadingOrder => ("Reverse reading direction", "読む方向を反転"),
    CommandReloadFolderOrder => ("Reload folder order", "フォルダーの並び順を再読み込み"),
    CommandUndo => ("Undo edit", "編集を元に戻す"),
    CommandRedo => ("Redo edit", "編集をやり直す"),
    CommandApplyCrop => ("Apply crop selection", "選択範囲で切り抜く"),
    CommandRotateClockwise => ("Rotate clockwise", "時計回りに回転"),
    CommandRotateCounterclockwise => ("Rotate counterclockwise", "反時計回りに回転"),
    CommandRotateFineClockwise => ("Rotate clockwise by 5 degrees", "時計回りに5度回転"),
    CommandRotateFineCounterclockwise => ("Rotate counterclockwise by 5 degrees", "反時計回りに5度回転"),
    CommandFlipHorizontal => ("Flip horizontally", "左右反転"),
    CommandFlipVertical => ("Flip vertically", "上下反転"),
    CommandSetTrimStart => ("Set time selection start", "時間範囲の開始位置を設定"),
    CommandSetTrimEnd => ("Set time selection end", "時間範囲の終了位置を設定"),
    CommandDeleteTimeSelection => ("Delete selected time", "選択した時間範囲を削除"),
    CommandKeepTimeSelection => ("Keep only selected time", "選択した時間範囲だけ残す"),
    CommandVolumeDown => ("Decrease volume", "音量を下げる"),
    CommandVolumeUp => ("Increase volume", "音量を上げる"),
    CommandToggleMute => ("Toggle mute", "ミュートを切り替え"),
    CommandCycleVolumeStep => ("Cycle volume step (2% / 5% / 10%)", "音量の調整幅を切り替え（2%／5%／10%）"),
    CommandVolumeStepTwo => ("Listening volume step: 2%", "再生音量の調整幅：2%"),
    CommandVolumeStepFive => ("Listening volume step: 5%", "再生音量の調整幅：5%"),
    CommandVolumeStepTen => ("Listening volume step: 10%", "再生音量の調整幅：10%"),
    CommandAudioRepeatOff => ("Audio repeat: off", "音声リピート：オフ"),
    CommandAudioRepeatAll => ("Audio repeat: all", "音声リピート：すべて"),
    CommandAudioRepeatOne => ("Audio repeat: one", "音声リピート：1曲"),
    CommandFolderNavigationStop => ("Folder navigation: stop at ends", "フォルダー内の移動：端で停止"),
    CommandFolderNavigationLoop => ("Folder navigation: loop at ends", "フォルダー内の移動：端でループ"),
    CommandRateDown => ("Decrease playback rate", "再生速度を下げる"),
    CommandRateUp => ("Increase playback rate", "再生速度を上げる"),
    CommandResetRate => ("Reset playback rate", "再生速度をリセット"),
    CommandDeleteFile => ("Delete file", "ファイルを削除"),
    CommandRenameFile => ("Rename file...", "ファイル名を変更..."),
    CommandMoveFile => ("Move file...", "ファイルを移動..."),
    CommandSave => ("Save", "保存"),
    CommandExportAs => ("Save as", "名前を付けて保存"),
    CommandAudioExportOptions => ("Audio export options", "音声の書き出し設定"),
    CommandMetadataExportOptions => ("Metadata export options", "メタデータの書き出し設定"),
    CommandExportAudio => ("Export audio only", "音声のみを書き出し"),
    CommandExportFrame => ("Export current frame (PNG)", "現在のフレームを書き出し（PNG）"),
    CommandToggleTimeline => ("Toggle editing timeline", "編集タイムラインを切り替え"),
    CommandToggleGridMenu => ("Toggle grid menu", "グリッドメニューを切り替え"),
    CommandExportQualityHigh => ("Export quality: High quality", "書き出し品質：高品質"),
    CommandExportQualityBalanced => ("Export quality: Balanced", "書き出し品質：バランス"),
    CommandExportQualitySmaller => ("Export quality: Smaller file", "書き出し品質：ファイルサイズ優先"),
    CommandToggleHardwareEncode => ("Prefer hardware encoding", "ハードウェアエンコードを優先"),
    CommandPreviousImage => ("Previous image", "前の画像"),
    CommandNextImage => ("Next image", "次の画像"),
    CommandFirstImage => ("First image in folder", "フォルダーの最初の画像"),
    CommandLastImage => ("Last image in folder", "フォルダーの最後の画像"),
    CommandIncreaseReadingFirstPage => ("Show more images on the first reading page", "最初の見開きの画像を増やす"),
    CommandDecreaseReadingFirstPage => ("Show fewer images on the first reading page", "最初の見開きの画像を減らす"),
    CommandCloseOtherTabs => ("Close other tabs", "ほかのタブを閉じる"),
    CommandCloseTabsLeft => ("Close tabs to the left", "左側のタブを閉じる"),
    CommandCloseTabsRight => ("Close tabs to the right", "右側のタブを閉じる"),
    CommandCloseAllTabs => ("Close all tabs", "すべてのタブを閉じる"),
    CommandReopenClosedTab => ("Reopen closed tab", "閉じたタブを開き直す"),
    CommandCopyFilePath => ("Copy file path", "ファイルのパスをコピー"),
    CommandRevealFile => ("Reveal in File Explorer", "エクスプローラーで表示"),
    CommandCopyImage => ("Copy image or selection", "画像または選択範囲をコピー"),
    CommandResizeImage => ("Resize / resample image", "画像のサイズ変更／再サンプリング"),
    CommandToggleImageInterpolation => ("Toggle image interpolation (smooth / nearest)", "画像の補間を切り替え（滑らか／ニアレスト）"),
    CommandToggleImageMinification => ("Toggle image minification (high quality / fast)", "画像の縮小表示を切り替え（高品質／高速）"),
    CommandPreviousVideoFrame => ("Previous video frame", "前の動画フレーム"),
    CommandNextVideoFrame => ("Next video frame", "次の動画フレーム"),
    CommandJumpImagesBackward1 => ("Jump backward 1 image", "1枚前の画像へ移動"),
    CommandJumpImagesBackward2 => ("Jump backward 2 images", "2枚前の画像へ移動"),
    CommandJumpImagesBackward3 => ("Jump backward 3 images", "3枚前の画像へ移動"),
    CommandJumpImagesBackward4 => ("Jump backward 4 images", "4枚前の画像へ移動"),
    CommandJumpImagesBackward5 => ("Jump backward 5 images", "5枚前の画像へ移動"),
    CommandJumpImagesBackward6 => ("Jump backward 6 images", "6枚前の画像へ移動"),
    CommandJumpImagesBackward7 => ("Jump backward 7 images", "7枚前の画像へ移動"),
    CommandJumpImagesBackward8 => ("Jump backward 8 images", "8枚前の画像へ移動"),
    CommandJumpImagesBackward9 => ("Jump backward 9 images", "9枚前の画像へ移動"),
    CommandJumpImagesBackward10 => ("Jump backward 10 images", "10枚前の画像へ移動"),
    CommandJumpImagesForward1 => ("Jump forward 1 image", "1枚先の画像へ移動"),
    CommandJumpImagesForward2 => ("Jump forward 2 images", "2枚先の画像へ移動"),
    CommandJumpImagesForward3 => ("Jump forward 3 images", "3枚先の画像へ移動"),
    CommandJumpImagesForward4 => ("Jump forward 4 images", "4枚先の画像へ移動"),
    CommandJumpImagesForward5 => ("Jump forward 5 images", "5枚先の画像へ移動"),
    CommandJumpImagesForward6 => ("Jump forward 6 images", "6枚先の画像へ移動"),
    CommandJumpImagesForward7 => ("Jump forward 7 images", "7枚先の画像へ移動"),
    CommandJumpImagesForward8 => ("Jump forward 8 images", "8枚先の画像へ移動"),
    CommandJumpImagesForward9 => ("Jump forward 9 images", "9枚先の画像へ移動"),
    CommandJumpImagesForward10 => ("Jump forward 10 images", "10枚先の画像へ移動"),
    CommandSelectAspectSquare => ("Select 1:1 aspect ratio", "縦横比1:1で選択"),
    CommandSelectAspectFourThree => ("Select 4:3 aspect ratio", "縦横比4:3で選択"),
    CommandSelectAspectThreeFour => ("Select 3:4 aspect ratio", "縦横比3:4で選択"),
    CommandSelectAspectThreeTwo => ("Select 3:2 aspect ratio", "縦横比3:2で選択"),
    CommandSelectAspectTwoThree => ("Select 2:3 aspect ratio", "縦横比2:3で選択"),
    CommandSelectAspectSixteenNine => ("Select 16:9 aspect ratio", "縦横比16:9で選択"),
    CommandSelectAspectNineSixteen => ("Select 9:16 aspect ratio", "縦横比9:16で選択"),
    CommandFreeRotateImage => ("Free rotate image", "画像を自由回転"),
    CommandFreeRotateVideo => ("Free rotate video", "動画を自由回転"),
    CommandResizeVideo => ("Resize / resample video", "動画のサイズ変更／再サンプリング"),
    CommandStepAudioBackward => ("Step audio backward (10 ms)", "音声を10ms戻す"),
    CommandStepAudioForward => ("Step audio forward (10 ms)", "音声を10ms進める"),
}
