//! Typed templates keep interpolation checked for every supported language.
use super::Language;

pub fn reading_status_parts(
    language: Language,
    pages_hint: &str,
    pages: usize,
    first_hint: &str,
    first: usize,
) -> [String; 2] {
    [
        reading_pages(language, pages_hint, pages),
        reading_first(language, first_hint, first),
    ]
}

pub fn reading_status(
    language: Language,
    pages_hint: &str,
    pages: usize,
    first_hint: &str,
    first: usize,
) -> String {
    reading_status_parts(language, pages_hint, pages, first_hint, first).join(" · ")
}

macro_rules! templates {
    ($($name:ident($($arg:ident: $ty:ty),*) => ($english:literal, $japanese:literal),)*) => {
        $(pub fn $name(language: Language, $($arg: $ty),*) -> String {
            match language {
                Language::English => format!($english, $($arg = $arg),*),
                Language::Japanese => format!($japanese, $($arg = $arg),*),
            }
        })*
    };
}

templates! {
    audio_tempo_failed(error: &str) => ("audio tempo processing failed: {error}", "音声の速度処理に失敗しました: {error}"),
    audio_unsupported_format(rate: u32, channels: u16) => ("unsupported audio format: {rate} Hz, {channels} channels", "未対応の音声形式です: {rate} Hz、{channels}チャンネル"),
    audio_wasapi_failed(error: &str) => ("WASAPI output failed: {error}", "WASAPI音声出力に失敗しました: {error}"),
    playback_probe_failed(error: &str) => ("media probing failed: {error}", "メディアの情報を取得できませんでした: {error}"),
    playback_audio_failed(error: &str) => ("audio output failed: {error}", "音声出力に失敗しました: {error}"),
    playback_thread_failed(error: &str) => ("the decode thread could not start: {error}", "デコード処理を開始できませんでした: {error}"),
    background_pipeline_recovery_failed(error: &str) => ("Background pipeline recovery failed: {error}", "バックグラウンドの再生処理を復旧できません: {error}"),
    render_d3d11(error: &str) => ("D3D11 failed: {error}", "D3D11の処理に失敗しました: {error}"),
    render_device_removed(error: &str) => ("the D3D11 device was removed: {error}", "D3D11デバイスを利用できなくなりました: {error}"),
    graphics_device_recovery_failed(error: &str) => ("D3D11 device recovery failed: {error}", "D3D11デバイスを復旧できません: {error}"),
    graphics_surface_recovery_failed(error: &str) => ("D3D11 surface recovery failed: {error}", "D3D11の表示領域を復旧できません: {error}"),
    graphics_pipeline_recovery_failed(error: &str) => ("D3D11 pipeline recovery failed: {error}", "D3D11の再生処理を復旧できません: {error}"),
    detailed_waveform_failed(error: &str) => ("Detailed waveform unavailable: {error}", "詳細な波形を取得できません: {error}"),
    update_http_status(status: u32) => ("Update server returned HTTP {status}", "更新サーバーがHTTP {status}を返しました"),
    update_helper_exited(status: &str, detail: &str) => ("Update helper exited before readiness ({status}): {detail}", "更新用の補助プロセスが準備完了前に終了しました（{status}）: {detail}"),
    update_unavailable(error: &str) => ("Update unavailable: {error}", "更新を利用できません: {error}"),
    language_restart_failed(error: &str) => ("towavue could not restart: {error}\nStart towavue manually to apply the saved language.", "towavueを再起動できませんでした: {error}\n手動でtowavueを起動すると、保存した表示言語が適用されます。"),
    image_open_failed(error: &str) => ("could not open image: {error}", "画像を開けません: {error}"),
    image_decode_failed(error: &str) => ("could not decode image: {error}", "画像を読み込めません: {error}"),
    gif_decode_failed(error: &str) => ("could not decode GIF: {error}", "GIFを読み込めません: {error}"),
    ffmpeg_image_decode_failed(error: &str) => ("FFmpeg could not decode image: {error}", "FFmpegで画像を読み込めません: {error}"),
    avif_decode_failed(error: &str) => ("could not decode AVIF: {error}", "AVIFを読み込めません: {error}"),
    png_decode_failed(error: &str) => ("could not decode PNG: {error}", "PNGを読み込めません: {error}"),
    apng_encode_failed(error: &str) => ("could not encode APNG export frames: {error}", "書き出し用のAPNGフレームを生成できません: {error}"),
    frame_extract_failed(error: &str) => ("could not extract video frame: {error}", "動画フレームを取り出せません: {error}"),
    ffmpeg_decode_failed(error: &str) => ("FFmpeg failed: {error}", "FFmpegの処理に失敗しました: {error}"),
    hardware_decode_unavailable(error: &str) => ("D3D11VA is unavailable: {error}", "D3D11VAを利用できません: {error}"),
    decode_worker_start_failed(error: &str) => ("a decode worker could not start: {error}", "メディアの読み込み処理を開始できません: {error}"),
    image_texture_limit(limit: usize) => ("Image dimensions exceed this graphics device's {limit}px texture limit", "画像サイズがこのGPUの画像サイズ上限（{limit}px）を超えています"),
    file_preview(path: &str) => ("Preview: {path}", "プレビュー: {path}"),
    tab_metadata_unavailable(error: &str) => ("Tab metadata unavailable: {error}", "タブのメタデータを取得できません: {error}"),
    recent_files_unavailable(error: &str) => ("Recent files unavailable: {error}", "最近使ったファイルを取得できません: {error}"),
    export_start_failed(error: &str) => ("could not start FFmpeg export: {error}", "FFmpegの書き出しを開始できませんでした: {error}"),
    ffmpeg_export_failed(error: &str) => ("FFmpeg export failed: {error}", "FFmpegの書き出しに失敗しました: {error}"),
    export_output_failed(error: &str) => ("could not prepare or publish export: {error}", "書き出しの準備または保存先への書き込みに失敗しました: {error}"),
    file_operation_failed(error: &str) => ("file operation failed: {error}", "ファイル操作に失敗しました: {error}"),
    windows_file_operation_failed(error: &str) => ("Windows file operation failed: {error}", "Windowsのファイル操作に失敗しました: {error}"),
    file_deletion_recovery(message: &str, directory: &str) => ("file deletion failed and the original source cannot be verified: {message}; retained file directory: {directory}", "ファイルの削除に失敗し、元ファイルの状態を確認できません: {message}。保持したファイルのフォルダー: {directory}"),
    source_save_failed(error: &str) => ("source save failed: {error}", "上書き保存に失敗しました: {error}"),
    source_replacement_recovery(message: &str, directory: &str) => ("source replacement needs recovery: {message}; preserved files: {directory}", "元ファイルの置き換えに復旧が必要です: {message}。保持したファイル: {directory}"),
    configuration_missing_equals(file: &str, line: usize) => ("{file} line {line} is missing '='", "{file}の{line}行目に「=」がありません"),
    configuration_unknown_command(file: &str, line: usize) => ("unknown command on {file} line {line}", "{file}の{line}行目に不明なコマンドがあります"),
    configuration_invalid_shortcut(line: usize) => ("invalid shortcut on shortcuts.conf line {line}", "shortcuts.confの{line}行目のショートカットが不正です"),
    configuration_unknown_media_kind(line: usize) => ("unknown media kind on grid.conf line {line}", "grid.confの{line}行目のメディア種別が不明です"),
    configuration_grid_count(line: usize, count: usize) => ("grid.conf line {line} has {count} commands; expected 16", "grid.confの{line}行目にコマンドが{count}個あります。16個指定してください"),
    configuration_fallback(details: &str, file_menu: &str, reload: &str) => ("Using built-in defaults for the settings below. Existing configuration files have not been changed.\n\n{details}\n\nCorrect these files, then choose {file_menu} > {reload} from the towavue menu.", "以下の設定には初期設定を使用しています。既存の設定ファイルは変更していません。\n\n{details}\n\nファイルを修正してから、towavueのメニューで「{file_menu}」>「{reload}」を選択してください。"),
    selection_edge_focus(label: &str, value: u32) => ("{label}: {value} · Arrow keys adjust", "{label}: {value} · 矢印キーで調整"),
    track_duration_suffix(time: &str) => (" · Duration {time}", " · 長さ {time}"),
    preview_near(time: &str) => ("Preview near {time}", "{time}付近のプレビュー"),
    seek_preview_unavailable(time: &str) => ("{time} · No preview", "{time} · プレビューなし"),
    audio_order_failed(error: &str) => ("Audio order unavailable: {error}", "音声ファイルの並び順を取得できません: {error}"),
    frame_step_failed(error: &str) => ("Frame step: {error}", "コマ送り: {error}"),
    hold_speed_progress(progress: u8, target: &str, hint: &str) => ("2× · {progress}% to lock {target}{hint}", "2× · {target}への固定まで{progress}%{hint}"),
    image_paste_failed(error: &str) => ("Could not paste image: {error}", "画像を貼り付けられませんでした: {error}"),
    playback_volume_save_failed(error: &str) => ("Could not save playback volume: {error}", "再生音量を保存できませんでした: {error}"),
    video_resume_failed(error: &str) => ("Video resume unavailable: {error}", "動画の再生位置を復元できません: {error}"),
    video_position_save_failed(error: &str) => ("Could not save video position: {error}", "動画の再生位置を保存できませんでした: {error}"),
    video_positions_clear_failed(error: &str) => ("Could not clear video positions: {error}", "動画の再生位置を消去できませんでした: {error}"),
    selected_aspect(x: u32, y: u32, width: u32, height: u32) => ("Selection {x}:{y} ({width} x {height} pixels)", "選択範囲 {x}:{y}（{width} × {height} ピクセル）"),
    saved_file(path: &str) => ("Saved {path}", "保存しました: {path}"),
    track_drag_failed(error: &str) => ("Could not start track drag: {error}", "曲のドラッグ操作を開始できませんでした: {error}"),
    video_export_quality(label: &str) => ("Video export quality: {label}", "動画の書き出し品質: {label}"),
    tab_move_failed(error: &str) => ("Could not move tab: {error}", "タブを移動できませんでした: {error}"),
    tab_drag_feedback_failed(error: &str) => ("Could not show tab drag feedback: {error}", "タブのドラッグ中の表示を更新できませんでした: {error}"),
    dragged_media_open_failed(error: &str) => ("Could not open dragged media: {error}", "ドラッグしたメディアを開けませんでした: {error}"),
    moved_file(path: &str) => ("File moved: {path}", "ファイルを移動しました: {path}"),
    copied_source_retained(path: &str) => ("A copy was created at {path}; the original could not be removed and remains open.", "コピーを作成しました: {path}。元ファイルを削除できなかったため、元ファイルを開いたままにしています。"),
    delete_preference_failed(message: &str, error: &str) => ("{message} The confirmation preference could not be saved: {error}", "{message} 削除確認の設定を保存できませんでした: {error}"),
    open_failed(path: &str, error: &str) => ("Could not open {path}: {error}", "開けませんでした: {path}: {error}"),
    unsupported_media(path: &str) => ("Unsupported media: {path}", "未対応のメディアです: {path}"),
    duration_worker_failed(error: &str) => ("Duration worker unavailable: {error}", "メディアの長さを取得する処理を開始できません: {error}"),
    no_folder_media(path: &str) => ("No supported media in {path}", "対応するメディアがありません: {path}"),
    revealed_file(path: &str) => ("Selected in Explorer: {path}", "エクスプローラーで選択しました: {path}"),
    reveal_failed(error: &str) => ("Could not reveal file: {error}", "エクスプローラーでファイルを表示できませんでした: {error}"),
    copied_image(width: u32, height: u32) => ("Copied image {width} × {height} px", "画像をコピーしました {width} × {height} px"),
    image_copy_failed(error: &str) => ("Could not copy image: {error}", "画像をコピーできませんでした: {error}"),
    duration_failed(error: &str) => ("Duration unavailable: {error}", "メディアの長さを取得できません: {error}"),
    waveform_failed(error: &str) => ("Waveform unavailable: {error}", "波形を取得できません: {error}"),
    window_action_failed(error: &str) => ("Could not perform window action: {error}", "ウィンドウ操作を実行できませんでした: {error}"),
    grid_reload_failed(error: &str) => ("Grid reload failed: {error}", "グリッドを再読み込みできませんでした: {error}"),
    shortcuts_reload_failed(error: &str) => ("Shortcut reload failed: {error}", "ショートカットを再読み込みできませんでした: {error}"),
    image_copy_start_failed(error: &str) => ("Could not start image copy: {error}", "画像のコピーを開始できませんでした: {error}"),
    listening_volume_step(step: u8) => ("Listening volume step: {step}%", "再生音量の調整幅: {step}%"),
    cropped_size(width: u32, height: u32) => ("Crop {width} × {height} px (source unchanged)", "{width} × {height} pxに切り抜きました（元ファイルは変更していません）"),
    preview_cache_failed(error: &str) => ("preview cache I/O failed: {error}", "プレビューキャッシュの読み書きに失敗しました: {error}"),
    preview_image_decode_failed(error: &str) => ("could not decode generated preview: {error}", "生成したプレビューを読み込めません: {error}"),
    preview_start_failed(program: &str, error: &str) => ("could not start {program}: {error}", "{program}を起動できません: {error}"),
    preview_generate_failed(error: &str) => ("FFmpeg preview generation failed: {error}", "FFmpegのプレビュー生成に失敗しました: {error}"),
    preview_input_failed(error: &str) => ("preview input preparation failed: {error}", "プレビューの入力を準備できません: {error}"),
    image_resample_reason(error: &str) => ("Could not resample image: {error}", "画像を再サンプリングできません: {error}"),
    image_resample_failed(error: &str) => ("Could not resample image: {error}. Undo to restore the previous edit.", "画像を再サンプリングできませんでした: {error}。「元に戻す」で前の編集状態に戻せます。"),
    speed_duration_limits(min: f64, max: f64) => ("Speed must be between {min:.3}x and {max:.3}x.", "速度は{min:.3}倍から{max:.3}倍の範囲で指定してください。"),
    preview_rate(rate: f32) => ("Playback speed {rate:.2}\u{00d7}", "\u{518d}\u{751f}\u{901f}\u{5ea6} {rate:.2}\u{00d7}"),
    rate_edited(rate: f32) => ("Rate {rate:.2}× · playback and export (source unchanged)", "速度 {rate:.2}× · 再生と書き出しに適用（元ファイルは変更していません）"),
    trim_edited(start: &str, end: &str) => ("Trim {start} – {end} · playback and export", "トリミング {start} – {end} · 再生と書き出しに適用"),
    exported_file(prefix: &str, path: &str, encoder: &str) => ("{prefix} {path} ({encoder} encode)", "{prefix} {path}（{encoder}エンコード）"),
    selection_rectangle(x: u32, y: u32, width: u32, height: u32) => ("Selection(XY:{x},{y} · {width}×{height}px)", "選択範囲(XY:{x},{y} · {width}×{height}px)"),
    detach_failed(error: &str) => ("Could not detach tab: {error}", "タブを別のウィンドウに移動できませんでした: {error}"),
    new_window_failed(error: &str) => ("Could not open new window: {error}", "新しいウィンドウを開けませんでした: {error}"),
    reading_drag_failed(error: &str) => ("Could not start reading drag: {error}", "読書モードのドラッグ操作を開始できませんでした: {error}"),
    image_resample_notice(error: &str) => ("Could not resample image: {error} · Undo to restore the previous edit.", "画像を再サンプリングできませんでした: {error} · 「元に戻す」で前の編集状態に戻せます。"),
    image_load_failed(error: &str) => ("Could not load image: {error}", "画像を読み込めませんでした: {error}"),
    reading_pages_failed(count: usize, errors: &str) => ("Could not load {count} reading page(s): {errors}", "読書ページを{count}件読み込めませんでした: {errors}"),
    playback_failed(error: &str) => ("Could not play media: {error}", "メディアを再生できませんでした: {error}"),
    edit_grid_file(path: &str) => ("Edit {path}", "編集: {path}"),
    last_opened(date: &str) => ("Last opened: {date}", "最後に開いた日: {date}"),
    shortcuts_file(path: &str) => ("Shortcuts: {path}", "ショートカット設定: {path}"),
    status_zoom(value: &str) => ("{value} zoom", "表示倍率 {value}"),
    status_reduction(zoom: &str, reduction: &str) => ("{zoom}. {reduction}", "{zoom}。{reduction}"),
    status_speed(value: &str) => ("Speed {value}", "再生速度 {value}"),
    source_frame_rate(value: &str) => ("Source frame rate: {value} (stream-reported; independent of playback speed)", "元のフレームレート: {value}（ストリームの値。再生速度には依存しません）"),
    status_pixels(value: &str) => ("{value} pixels", "{value} ピクセル"),
    status_frames(count: usize) => ("{count} frames", "{count}フレーム"),
    status_animation_frames(count: usize) => ("{count} animation frames", "アニメーションのフレーム数: {count}"),
    status_modified(value: &str) => ("Modified (local): {value}", "更新日時（ローカル）: {value}"),
    time_focus(label: &str, time: &str) => ("{label}: {time} · Left/Right adjust", "{label}: {time} · ←／→で調整"),
    value_focus(label: &str, value: f64) => ("{label}: {value:.3} · Left/Right adjust", "{label}: {value:.3} · ←／→で調整"),
    timeline_length(value: &str) => ("Length {value}", "長さ {value}"),
    timeline_gain(value: f64) => ("Gain {value:.0}%", "倍率 {value:.0}%"),
    preview_unavailable(error: &str) => ("\nPreview unavailable: {error}", "\nプレビューを表示できません: {error}"),
    mute_named_tab(name: &str) => ("Mute tab: {name}", "タブをミュート: {name}"),
    unmute_named_tab(name: &str) => ("Unmute tab: {name}", "タブのミュートを解除: {name}"),
    reading_pages(pages_hint: &str, pages: usize) => ("{pages_hint}Reading {pages}", "{pages_hint}読書 {pages}ページ"),
    reading_first(first_hint: &str, first: usize) => ("{first_hint}first {first}", "{first_hint}先頭 {first}ページ"),
    calendar_month(name: &str, year: u16) => ("{name} {year}", "{year}年{name}"),
    calendar_day(name: &str, year: u16, day: u16) => ("{name} {day}, {year}", "{year}年{name}{day}日"),
    preparation_elapsed(phase: &str, time: &str) => ("{phase} · elapsed {time}", "{phase} · 経過時間 {time}"),
    tab_label(title: &str) => ("{title} tab", "{title} タブ"),
    close_title(title: &str) => ("Close {title}", "{title}を閉じる"),
    close_tab(title: &str) => ("Close tab: {title}", "タブを閉じる: {title}"),
    file_search_summary(shown: usize, matches: u64, skipped: u64) => ("Showing {shown} of {matches} matches; {skipped} entries skipped", "{matches}件中{shown}件を表示、{skipped}件をスキップ"),
    file_search_help(summary: &str) => ("{summary}\nUnreadable entries, links/junctions and folders deeper than 128 levels are skipped. Refine the query to narrow results.", "{summary}\n読み取れない項目、リンク／ジャンクション、128階層より深いフォルダーはスキップします。検索語を追加して結果を絞り込んでください。"),
    dialog_thread_failed(error: &str) => ("the file-dialog thread could not start: {error}", "ファイルダイアログの処理を開始できませんでした: {error}"),
    dialog_windows_failed(error: &str) => ("Windows file dialog failed: {error}", "Windowsのファイルダイアログでエラーが発生しました: {error}"),
    dialog_invalid_path(error: &str) => ("Windows returned an invalid UTF-16 path: {error}", "Windowsが返したパスの文字情報が不正です（UTF-16）: {error}"),
    dialog_export_failed(error: &str) => ("Could not prepare export formats: {error}", "書き出し形式を準備できませんでした: {error}"),
    native_delete(path: &str, retained: &str) => ("{path}\n\nThe file will be moved to the Recycle Bin.{retained}", "{path}\n\nこのファイルをごみ箱へ移動します。{retained}"),
    native_about_title(version: &str) => ("towavue / Version {version}", "towavue / バージョン {version}"),
    native_about_content(license: &str) => ("Windows media viewer created by <a href=\"author\">sheeta</a>\n\n<a href=\"repository\">GitHub</a> · <a href=\"website\">Website</a>\n\n{license}. Provided without warranty.", "<a href=\"author\">sheeta</a>が制作したWindows用メディアビューアー\n\n<a href=\"repository\">GitHub</a> · <a href=\"website\">ウェブサイト</a>\n\n{license}。無保証で提供されます。"),
    native_extension_mismatch(format: &str) => ("The filename extension does not match {format}. Change the filename extension or select the matching file type.", "ファイル名の拡張子が{format}と一致しません。拡張子を変更するか、一致するファイル形式を選択してください。"),
    native_update_notice(version: &str, failed: &str) => ("Version {version} is downloaded and ready to install.{failed}\n\nInstallation can take several minutes. towavue will close and reopen automatically.", "バージョン{version}をダウンロードしました。インストールできます。{failed}\n\nインストールには数分かかる場合があります。towavueは自動で終了し、起動し直します。"),
    native_recovery(error: &str) => ("Graphics could not be restored.\n\n{error}\n\nRetry: restore graphics at the saved playback position.\nCancel: keep all edits. Press Alt+F4 afterward to export or close.", "描画を復元できませんでした。\n\n{error}\n\n再試行：保存した再生位置で描画を復元します。\nキャンセル：すべての編集を保持します。その後Alt+F4を押すと、書き出しまたは終了を選択できます。"),
    native_save_guard(name: &str, save: &str) => ("{name}\n\n{save} Cancel keeps your edits and stops this action.", "{name}\n\n{save} キャンセルすると、編集内容を保持してこの操作を取り消します。"),
    native_export_error(error: &str) => ("Export failed. Your edits are retained.\n\n{error}", "書き出しに失敗しました。編集内容は保持されています。\n\n{error}"),
    about_failed(error: &str) => ("Could not show About: {error}", "アプリ情報を表示できませんでした: {error}"),
    link_failed(error: &str) => ("Could not open link: {error}", "リンクを開けませんでした: {error}"),
    update_notice_failed(error: &str) => ("Could not show the update notification: {error}", "更新通知を表示できませんでした: {error}"),
    confirmation_failed(error: &str) => ("Could not show the confirmation; edits kept: {error}", "確認を表示できませんでした。編集内容は保持されています: {error}"),
    language_save_failed(error: &str) => ("Could not save the language: {error}", "表示言語を保存できませんでした: {error}"),
    rotation_drag(angle: f32, help: &str) => ("Rotation: {angle:.1} degrees · {help}", "回転: {angle:.1}度 · {help}"),
    rotation_drag_invalid(error: &str) => ("{error} · Preview unchanged; release cancels", "{error} · プレビューは変更しません。離すとキャンセル"),
    rotation_cancelled(error: &str) => ("Rotation cancelled: {error}", "回転をキャンセルしました: {error}"),
    png_keyword(keyword: &str) => ("PNG keyword: {keyword}", "PNGのキーワード: {keyword}"),
    xmp_property(format: &str, property: &str) => ("{format} XMP property: {property}", "{format}のXMPプロパティ: {property}"),
    metadata_read_failed(error: &str) => ("Could not read metadata: {error}", "メタデータを読み取れませんでした: {error}"),
    pixel_size(width: u32, height: u32) => ("{width} × {height} px", "{width} × {height} px"),
    animation_resize_budget(frames: usize) => ("All {frames} animation frames must fit within 512 MiB.", "アニメーションの全{frames}フレームを512 MiB以内に収めてください。"),
    loudness_summary(integrated: f64, peak: f64) => ("{integrated:.1} LUFS / max {peak:.1} dBTP", "{integrated:.1} LUFS / 最大 {peak:.1} dBTP"),
    next_audio_export(options: &str) => ("Next export: {options}. Playback and edits unchanged.", "次回の書き出し: {options}。再生と編集内容は変更しません。"),
    release_menu(menu: &str) => ("Release to open the {menu} menu", "離すと「{menu}」メニューを開きます"),
    also_used_by(commands: &str) => ("Also used by: {commands}", "同じキーを使用: {commands}"),
    configure_keybinding(command: &str) => ("Configure keybinding: {command}", "キー割り当てを設定: {command}"),
    remove_recent_command(command: &str) => ("Remove {command} from Recently Used", "「{command}」を最近使用した履歴から削除"),
}
